module.exports = {
    TEACHER_COLLECTION: "teacher",
    SERVICEID: "VAe4ffd2a81521022333fe11a7f4066b49",
    ACCOUNTSID: "ACeb64975de3696c63c958ff627ab8472b",
    AUTH_TOCKEN: "ee311e0af9c26406896d25878c0001bc",
    STUDENT_COLLECTION: "student",
    TEACHER_collection: "image",
    STUDENT_DETAILS: "details",
    STUDENT_LOGIN: "studentlogin",
    STUDENT_ASSIGNED_WORK: "studentassignedwork",
    STUDENT_ASSIGNED_PDF: "givenwork",
    STUDENT_NOTE: "NOTEPDF",
    STUDENT_VIDEO: "vedio",
    STUDENT_NOTE_LINK: "studentlink",
    SUBMITTED_WORKS: "assignments",
    ANNOUNCEMENT: "announcement",
    STATUS: "status",
    STUDENT_NORMALEVENT: "normalevent",
    STUDENT_PAYEVENT: "payevent",
    STUDENT_PAYMENT: "payment",
    GALLERY: "gallery",
    TOKEN: "token",
    CHECK_PAYMENT: "checkpayment",
    PROGRESS: "progress",
    PAYTM: "paytm",
  };
  